### ISSUE TITLE
[Bloom] Losing focus on input-field when searching 

### ISSUE THREAD

**Issue by Sefohui** [spicetify/spicetify-themes#1043]
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version.
2. Your Spotify version is compatible with the `spicetify` version you are using.
3. You have the most recent version of the themes.
4. You followed the installation instructions for the theme you are using (please go through the entire theme README).

**Describe the bug**
When trying to search it will lose focus after a very short time of not typing anything so I have to click on the input field again to continue typing.

**To Reproduce**
1. Click the search icon
2. Start typing and make a slight pause.

**Expected behavior**
When I tried on different themes it will do the search but still keep focus on the input field so that I can continue typing.

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'listen')
    at stats (extension.js:558:32)
    at extension.js:563:5
    at extension.js:564:3
favicon.ico:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
extension.js:8 Initializing Spicetify Marketplace v0.9.2
spicetifyWrapper.js:2412 TypeError: Cannot read properties of null (reading '1')
    at checkForUpdate (spicetifyWrapper.js:2301:75)
checkForUpdate @ spicetifyWrapper.js:2412
extension.js:8 Loaded Marketplace extension
group-session.js?time=1710774865573:676 [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.
initialize @ group-session.js?time=1710774865573:676
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
gew4-spclient.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:1 provider:transport resolve error k Object
f @ vendor~xpui.js:1
index.html:1 Uncaught (in promise) k
index.html:1 Access to image at 'https://lexicon-assets.spotifycdn.com/DJ-Beta-CoverArt-300.jpg' from origin 'https://xpui.app.spotify.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
lexicon-assets.spotifycdn.com/DJ-Beta-CoverArt-300.jpg:1 
        
        
       Failed to load resource: net::ERR_FAILED
spclient.wg.spotify.com/social-connect/v2/sessions/current?local_device_id=f5282077e5d9aeda56c8206e81d4b561711a61c8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
spclient.wg.spotify.com/social-connect/v2/sessions/current?local_device_id=f5282077e5d9aeda56c8206e81d4b561711a61c8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
spclient.wg.spotify.com/social-connect/v2/sessions/current?local_device_id=f5282077e5d9aeda56c8206e81d4b561711a61c8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
spclient.wg.spotify.com/social-connect/v2/sessions/current?local_device_id=f5282077e5d9aeda56c8206e81d4b561711a61c8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
spclient.wg.spotify.com/social-connect/v2/sessions/current?local_device_id=f5282077e5d9aeda56c8206e81d4b561711a61c8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
spclient.wg.spotify.com/social-connect/v2/sessions/current?local_device_id=f5282077e5d9aeda56c8206e81d4b561711a61c8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
spclient.wg.spotify.com/social-connect/v2/sessions/current?local_device_id=f5282077e5d9aeda56c8206e81d4b561711a61c8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
spclient.wg.spotify.com/social-connect/v2/sessions/current?local_device_id=f5282077e5d9aeda56c8206e81d4b561711a61c8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
spicetifyWrapper.js:368 
        
        
       GET https://spclient.wg.spotify.com/social-connect/v2/sessions/current?local_device_id=f5282077e5d9aeda56c8206e81d4b561711a61c8 net::ERR_ABORTED 404 (Not Found)
```

**Specifics (please complete the following information):**
 - OS: Windows 11
 - Spotify version: 1.2.33.1039.g8ddb5918
 - Spicetify version: v2.34.1
 - Theme name: Bloom

**Comment by harbassan** [comment]
I don't manage the Bloom theme, but if there's already an issue on that repo you'll have to wait for someone else to fix it, but i should be a simple css fix anyways.
