### ISSUE TITLE
[text] Playlists, playlists text and marketplace are misaligned on sidebar

### ISSUE THREAD

**Issue by jungby** [spicetify/spicetify-themes#1057]
**Describe the bug**
After updating the playlists are now misaligned, the cart for marketplace was already like that but only with this theme

**To Reproduce**
1. Open Spotify
2. See the playlists on the left

**Expected behavior**
They should be aligned when compact or not.

**Screenshots**
![image](https://github.com/spicetify/spicetify-themes/assets/86584280/4313337e-a3c9-4e0c-9484-139dda0e0357)
![image](https://github.com/spicetify/spicetify-themes/assets/86584280/8817dc3a-e678-413f-aa2c-a777518f5153)

**Logs**
```console
index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
4151.css:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
favicon.ico:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
extension.js:8 Initializing Spicetify Marketplace v0.9.4
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
extension.js:8 Loaded Marketplace extension
gue1-spclient.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:1 provider:transport resolve error k Object
f @ vendor~xpui.js:1
index.html:1 Uncaught (in promise) k
xpui.js:1 Error: Unexpectedly hit unreachable code! Unhandled discriminated union member: {"__typename":"HomeSpotlightSectionData"}
    at i (xpui.js:1:2235907)
    at r (xpui.js:1:2236037)
    at ds (home-v2.js:1:20888)
    at Ta (vendor~xpui.js:1:1914117)
    at Tc (vendor~xpui.js:1:1970972)
    at yl (vendor~xpui.js:1:1960124)
    at vl (vendor~xpui.js:1:1960052)
    at _l (vendor~xpui.js:1:1959915)
    at ll (vendor~xpui.js:1:1957056)
    at Wi (vendor~xpui.js:1:1897958)
r @ xpui.js:1
xpui.js:1 Error: Unexpectedly hit unreachable code! Unhandled discriminated union member: {"__typename":"HomeSpotlightSectionData"}
    at i (xpui.js:1:2235907)
    at r (xpui.js:1:2236037)
    at ds (home-v2.js:1:20888)
    at Ta (vendor~xpui.js:1:1914117)
    at Cs (vendor~xpui.js:1:1925748)
    at Tc (vendor~xpui.js:1:1971839)
    at yl (vendor~xpui.js:1:1960124)
    at vl (vendor~xpui.js:1:1960052)
    at _l (vendor~xpui.js:1:1959915)
    at ll (vendor~xpui.js:1:1957056)
```

**Specifics (please complete the following information):**
 - OS: Windows 11 Pro 23H2
 - Spotify version: 1.2.36.959.g04bf500c
 - Spicetify version: 2.36.10
 - Theme name: text

**Comment by 4310V343k** [comment]
going to add onto that - there is a lot of unused real estate on an artist's page. it is even more clearly seen on bigger displays
![image](https://github.com/spicetify/spicetify-themes/assets/56449763/66c5c5d6-3b85-4d60-b836-12d6a2c4cde9)

**Comment by DaitiDay** [comment]
Don't know if it's a "proper" fix, but I've changed
```
.main-yourLibraryX-rowCover {
    height: 24px !important;
    width: 24px !important;
    -webkit-box-shadow: none;
    box-shadow: none;
}
```
to
```
.main-yourLibraryX-rowCover {
    height: 48px !important;
    width: 48px !important;
    -webkit-box-shadow: none;
    box-shadow: none;
}
```
in the `user.css` file, and the icons are now back to what they should look like.
