### ISSUE TITLE
[StarryNight] - only detects 1/3 of the screen

### ISSUE THREAD

**Issue by befabry** [spicetify/spicetify-themes#1134]
**Prerequisites**

Spicetify version : spicetify v2.38.7
Spotify-launcher : extra/spotify-launcher 0.6.1-1 from the AUR
Latest version of the themes applied

**Describe the bug**
The theme apply to 1/3rd of my vertical length, nothing's detected below

**To Reproduce**
1. Fresh copy of the themes
2. Start the Spotify launcher

**Expected behavior**
It detects the whole screen

**Screenshots**
![image](https://github.com/user-attachments/assets/2369bbad-afbb-4eb9-abe3-822f0d970879)

**Logs**

```console
index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
spicetifyWrapper.js:461 [spicetifyWrapper] Waiting for required webpack modules to load
xpui.js:1 Uncaught Error: spotify.connectivity.pubsub.esperanto.proto.PubSub.addOnNewConnectionID failed with code: Resolver not found!
    at onFailure (xpui.js:1:2137546)
xpui.js:1 Uncaught Error: spotify.ads.esperanto.slots.proto.Slots.SubSlot failed with code: Resolver not found!
    at onFailure (xpui.js:1:2137546)
xpui.js:1 Uncaught (in promise) Error: spotify.ads.esperanto.slots.proto.Slots.CreateSlot failed with code: Resolver not found!
    at onFailure (xpui.js:1:2137546)
xpui.js:1 Uncaught (in promise) Error: spotify.ads.esperanto.settings.proto.Settings.updateSlotEnabled failed with code: Resolver not found!
    at onFailure (xpui.js:1:2137546)
favicon.ico:1 
 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
xpui.js:1 NotFoundError: SUB request to sp://desktop/v1/upgrade/status failed with status code 404
    at l.onSuccess (xpui.js:1:2129248)
    at onSuccess (xpui.js:1:2129062)
spicetifyWrapper.js:332 Uncaught TypeError: Cannot read properties of undefined (reading '_map')
    at addMissingPlatformAPIs (spicetifyWrapper.js:332:53)
spicetifyWrapper.js:482 [spicetifyWrapper] All required webpack modules loaded
xpui.js:1 Uncaught (in promise) Error: spotify.ads.esperanto.ads.proto.Ads.GetAds failed with code: Resolver not found!
    at onFailure (xpui.js:1:2137546)
gew1-spclient.spotif…/sessions/current:1 
 Failed to load resource: the server responded with a status of 404 ()
gew1-spclient.spotif…/v3/configuration:1 
 Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:1 provider:transport resolve error 
T
 
Object
index.html:1 Uncaught (in promise) 
T
theme.js:103 Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at handleLabelChange (theme.js:103:11)
    at MutationObserver.<anonymous> (theme.js:88:11)
vendor~xpui.js:1 Error: Invalid playlist response!
    at Po (xpui.js:1:1860264)
    at Do.getPlaylist (xpui.js:1:1861906)
    at async Do.getMetadata (xpui.js:1:1862132)

```

![image](https://github.com/user-attachments/assets/833ecdcd-2c1a-4f00-be62-52059ca05e6e)

**Specifics (please complete the following information):**
 - OS: Arch Linux Linux 6.12.6-273-tkg-pds x86_64
 - Spotify version extra/spotify-launcher 0.6.1-1
 - Spicetify version 2.38.7
 - Theme name : StarryNight Forest

**Comment by JJfriends** [comment]
Same issue here
