### ISSUE TITLE
[Flow] Breaks entire UI

### ISSUE THREAD

**Issue by entityknownevil34** [spicetify/spicetify-themes#850]
**Describe the bug**
Turning on the Flow theme breaks the entire spotify player(tested on 2 pcs with freshly installed spotify and spicetify)(maybe we're just dumb)

**To Reproduce**
1. Go to marketplace
2. Install and enable Flow
3. UI breaks

**Expected behavior**
To have the Flow theme running properly

**Screenshots**
![flow_screenshot](https://user-images.githubusercontent.com/115426948/194776866-c0cca4da-7d1d-454b-8537-6fd39cf2341d.png)
![flow_screenshot2](https://user-images.githubusercontent.com/115426948/194777086-f32bd456-049f-4552-b2de-44f97694aebe.png)

**Logs**
```
Preloading extensions and themes...
extension.js:1 Initializing Spicetify Marketplace v0.8.1
extension.js:6 Loaded Marketplace extension
xpui.js:1 Uncaught (in promise) NotFoundError: GET request to sp://ads/v1/settings/leaderboard failed with status code 404
    at e.value (xpui.js:1:2074536)
    at onSuccess (xpui.js:1:2074312)
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
extension.js:1 Object
extension.js:1 Parsed 34/34 extensions
extension.js:1 No more extension results
extension.js:1 Object
extension.js:1 Parsed 23/23 themes
extension.js:1 No more theme results
raw.githubusercontent.com/spicetify/spicetify-marketplace/main/manifest.json:1          Failed to load resource: the server responded with a status of 404 ()
pubads_impl_2022100301.js:10 The following functions are deprecated: googletag.pubads().setTagForChildDirectedTreatment(), googletag.pubads().clearTagForChildDirectedTreatment(), googletag.pubads().setRequestNonPersonalizedAds(), and googletag.pubads().setTagForUnderAgeOfConsent(). Please use googletag.pubads().setPrivacySettings() instead.
kv @ pubads_impl_2022100301.js:10
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/8696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-hpto.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/4453.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/7269.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/5392.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-v2.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/8419.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
extension.js:1          GET https://raw.githubusercontent.com/itsmeow/Spicetify-Canvas/master/manifest.json 404
I @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1          GET https://raw.githubusercontent.com/getomni/spicetify/main/manifest.json 404
I @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1          GET https://raw.githubusercontent.com/catppuccin/spicetify/main/manifest.json 404
I @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1          GET https://raw.githubusercontent.com/axieum/jasmine-spicetify-theme/master/manifest.json 404
I @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/leaderboard
spicetify-routes-marketplace.js:14 No theme set as installed
pubads_impl_2022100301.js:10 The following functions are deprecated: googletag.pubads().setTagForChildDirectedTreatment(), googletag.pubads().clearTagForChildDirectedTreatment(), googletag.pubads().setRequestNonPersonalizedAds(), and googletag.pubads().setTagForUnderAgeOfConsent(). Please use googletag.pubads().setPrivacySettings() instead.
kv @ pubads_impl_2022100301.js:10
(anonymous) @ pubads_impl_2022100301.js:18
(anonymous) @ pubads_impl_2022100301.js:10
(anonymous) @ pubads_impl_2022100301.js:18
(anonymous) @ pubads_impl_2022100301.js:6
(anonymous) @ pubads_impl_2022100301.js:6
(anonymous) @ about:srcdoc:72
qI.push @ pubads_impl_2022100301.js:18
(anonymous) @ pubads_impl_2022100301.js:18
(anonymous) @ pubads_impl_2022100301.js:6
(anonymous) @ pubads_impl_2022100301.js:18
(anonymous) @ pubads_impl_2022100301.js:18
(anonymous) @ pubads_impl_2022100301.js:18
extension.js:1          GET https://raw.githubusercontent.com/yougotwill/Koushi/main/manifest.json 404
I @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1          GET https://raw.githubusercontent.com/canbeardig/Spicetify-Orchis-Colours-v2/main/manifest.json 404
I @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1          GET https://raw.githubusercontent.com/okarin001/Onepunch/main/manifest.json 404
I @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1          GET https://raw.githubusercontent.com/Darkempire78/Dracula-Spicetify/master/manifest.json 404
I @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
spicetify-routes-marketplace.js:9          GET https://raw.githubusercontent.com/Darkempire78/Dracula-Spicetify/master/manifest.json 404
Vr @ spicetify-routes-marketplace.js:9
zr @ spicetify-routes-marketplace.js:9
loadPage @ spicetify-routes-marketplace.js:14
await in loadPage (async)
loadAmount @ spicetify-routes-marketplace.js:14
newRequest @ spicetify-routes-marketplace.js:14
componentDidMount @ spicetify-routes-marketplace.js:14
await in componentDidMount (async)
ps @ vendor~xpui.js:29
Rl @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
Ho @ vendor~xpui.js:29
Cl @ vendor~xpui.js:29
hl @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
Ho @ vendor~xpui.js:29
zo @ vendor~xpui.js:29
M @ vendor~xpui.js:29
_.port1.onmessage @ vendor~xpui.js:29
extension.js:1          GET https://raw.githubusercontent.com/aiden04/spicetify-gui/main/manifest.json 404
I @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
spicetify-routes-marketplace.js:9          GET https://raw.githubusercontent.com/aiden04/spicetify-gui/main/manifest.json 404
Vr @ spicetify-routes-marketplace.js:9
zr @ spicetify-routes-marketplace.js:9
loadPage @ spicetify-routes-marketplace.js:14
await in loadPage (async)
loadAmount @ spicetify-routes-marketplace.js:14
newRequest @ spicetify-routes-marketplace.js:14
componentDidMount @ spicetify-routes-marketplace.js:14
await in componentDidMount (async)
ps @ vendor~xpui.js:29
Rl @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
Ho @ vendor~xpui.js:29
Cl @ vendor~xpui.js:29
hl @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
Ho @ vendor~xpui.js:29
zo @ vendor~xpui.js:29
M @ vendor~xpui.js:29
_.port1.onmessage @ vendor~xpui.js:29
extension.js:1          GET https://raw.githubusercontent.com/th3an7/SpicetifyThings/master/manifest.json 404
I @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
spicetify-routes-marketplace.js:9          GET https://raw.githubusercontent.com/th3an7/SpicetifyThings/master/manifest.json 404
Vr @ spicetify-routes-marketplace.js:9
zr @ spicetify-routes-marketplace.js:9
loadPage @ spicetify-routes-marketplace.js:14
await in loadPage (async)
loadAmount @ spicetify-routes-marketplace.js:14
newRequest @ spicetify-routes-marketplace.js:14
componentDidMount @ spicetify-routes-marketplace.js:14
await in componentDidMount (async)
ps @ vendor~xpui.js:29
Rl @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
Ho @ vendor~xpui.js:29
Cl @ vendor~xpui.js:29
hl @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
Ho @ vendor~xpui.js:29
zo @ vendor~xpui.js:29
M @ vendor~xpui.js:29
_.port1.onmessage @ vendor~xpui.js:29
extension.js:1          GET https://raw.githubusercontent.com/nm-nvan/spicetify-twitter/main/manifest.json 404
I @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
spicetify-routes-marketplace.js:9          GET https://raw.githubusercontent.com/nm-nvan/spicetify-twitter/main/manifest.json 404
Vr @ spicetify-routes-marketplace.js:9
zr @ spicetify-routes-marketplace.js:9
loadPage @ spicetify-routes-marketplace.js:14
await in loadPage (async)
loadAmount @ spicetify-routes-marketplace.js:14
newRequest @ spicetify-routes-marketplace.js:14
componentDidMount @ spicetify-routes-marketplace.js:14
await in componentDidMount (async)
ps @ vendor~xpui.js:29
Rl @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
Ho @ vendor~xpui.js:29
Cl @ vendor~xpui.js:29
hl @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
Ho @ vendor~xpui.js:29
zo @ vendor~xpui.js:29
M @ vendor~xpui.js:29
_.port1.onmessage @ vendor~xpui.js:29
spicetify-routes-marketplace.js:9          GET https://raw.githubusercontent.com/Dueel/dotfiles/main/manifest.json 404
Vr @ spicetify-routes-marketplace.js:9
zr @ spicetify-routes-marketplace.js:9
loadPage @ spicetify-routes-marketplace.js:14
await in loadPage (async)
loadAmount @ spicetify-routes-marketplace.js:14
newRequest @ spicetify-routes-marketplace.js:14
componentDidMount @ spicetify-routes-marketplace.js:14
await in componentDidMount (async)
ps @ vendor~xpui.js:29
Rl @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
Ho @ vendor~xpui.js:29
Cl @ vendor~xpui.js:29
hl @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
Ho @ vendor~xpui.js:29
zo @ vendor~xpui.js:29
M @ vendor~xpui.js:29
_.port1.onmessage @ vendor~xpui.js:29
spicetify-routes-marketplace.js:14 Parsed 23/23 themes
spicetify-routes-marketplace.js:14 No more theme results
extension.js:1          GET https://raw.githubusercontent.com/einzigartigerName/spicetify-history/main/manifest.json 404
I @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
spicetify-routes-marketplace.js:9 {}
spicetify-routes-marketplace.js:9 null
spicetify-routes-marketplace.js:9 Installing theme marketplace:installed:spicetify/spicetify-themes/Flow/user.css
spicetify-routes-marketplace.js:9 {Pink: {…}, Green: {…}, Silver: {…}, Violet: {…}, Ocean: {…}} 'Pink'
spicetify-routes-marketplace.js:9 Installed
spicetify-routes-marketplace.js:6 Parsing CSS:  https://cdn.jsdelivr.net/gh/spicetify/spicetify-themes@master/Flow/user.css
spicetify-routes-marketplace.js:14 updateColourSchemes {Pink: {…}, Green: {…}, Silver: {…}, Violet: {…}, Ocean: {…}} Pink
spicetify-routes-marketplace.js:14 {manifest: {…}, type: 'theme', title: 'Flow', subtitle: 'Spicetify theme that has linear gradient effect and vertical playbar', authors: Array(4), …}
extension.js:1          GET https://raw.githubusercontent.com/FlafyDev/spotify-listen-together-server/main/manifest.json 404
```
might be a mess sorry

**Specifics (please complete the following information):**
 - OS: win10
 - Spotify version 1.1.95.893.g6cf4d40c
 - Spicetify version 2.14.0
 - Flow

**Comment by entityknownevil34** [comment]
Turning spotify on for the logs on the second pc has made Flow look like this now:

![Flow_screenshot3](https://user-images.githubusercontent.com/115426948/194777432-57bf275c-090f-4dde-ac96-66a15bfbdc56.png)
