### ISSUE TITLE
[Dreary] Playlists not able to scroll

### ISSUE THREAD

**Issue by realKeehan** [spicetify/spicetify-themes#914]
**Describe the bug**
There is no scroll bar on the playlists section nor is there an outline on them even though I enabled `spicetify config sidebar_config 1`

**To Reproduce**
Not sure but I can send my installed things if needed

**Expected behavior**
Be able to scroll through my playlists in the sidebar

**Screenshots**
![image](https://user-images.githubusercontent.com/41766284/232498358-e6631022-0e1c-4fda-9d1d-cf504f6c2581.png)

**Logs**

```console
Failed to load resource: the server responded with a status of 404 ()
extension.js:1 Initializing Spicetify Marketplace v0.8.5
extension.js:1 Loaded Marketplace extension
hidePodcasts.js?time=1681738153179:1 HidePodcasts: Loaded
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
hidePodcasts.js?time=1681738153179:5 / <section class=​"main-shelf-shelf Shelf" aria-label=​"Jump back in">​…​</section>​ flex 
hidePodcasts.js?time=1681738153179:5 Tagging carousel: Your shows
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:2001835)
    at onSuccess (xpui.js:1:2001649)
onError @ vendor~xpui.js:29
raw.githubusercontent.com/3raxton/spicetify-custom-apps-and-extensions/main/manifest.json:1          Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/TheRandomLabs/Scoop-Spotify/master/manifest.json:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/9692.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/8934.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-hpto.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-v2.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/7542.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
extension.js:1          GET https://raw.githubusercontent.com/catppuccin/spicetify/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1          GET https://raw.githubusercontent.com/itsmeow/Spicetify-Canvas/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1          GET https://raw.githubusercontent.com/getomni/spicetify/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1          GET https://raw.githubusercontent.com/schnensch0/ziro/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1          GET https://raw.githubusercontent.com/Darkempire78/Fast-BlockTheSpot-And-Spicetify-Update/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1          GET https://raw.githubusercontent.com/Darkempire78/Fast-BlockTheSpot-And-Spicetify-Update/main/manifest.json 404
```

**Specifics (please complete the following information):**
 - OS: [Windows]
 - Spotify version [Spotify for Windows
1.2.9.743.g85d9593d]
 - Spicetify version [Spicetify v2.17.2]
 - Dreary
 
![image](https://user-images.githubusercontent.com/41766284/232499645-1074879a-a7f1-42e2-9c99-21db1cc0afbf.png)

**Comment by realKeehan** [comment]
Theres also a seperate conflict with the `Hoverable Sections` Snippet where its impossible to follow artists

**Comment by CharlieS1103** [comment]
I haven't updated dreary in a while, at this point the theme is basically completely broken. Might be time to just remove it.

**Comment by harbassan** [comment]
@CharlieS1103 do you genuinely want to just remove it?

**Comment by CharlieS1103** [comment]
@harbassan Might just be best at some point unless someone wants to pick it up, I have no plans to update it.
