### ISSUE TITLE
[Dribbblish] Wrongly offset ui

### ISSUE THREAD

**Issue by YoinkedYoink** [spicetify/spicetify-themes#931]
When using the dribblish theme and no other plugins, the ui elements are offset wrong and overlap

**To Reproduce**
1. Install Dribblish using marketplace
2. Install the required Dribblish js using powershell
3. Open Spotify and see if the ui is offset

**Expected behavior**
The ui to not overlap and look clean and flush

**Screenshots**
![image](https://github.com/spicetify/spicetify-themes/assets/87105685/4f76564a-bffd-4fa1-8496-ad7ad73b28da)
![image](https://github.com/spicetify/spicetify-themes/assets/87105685/ce89af7f-ceed-489c-bc6d-a4d05ff3337f)

**Logs**
```console
Initializing Spicetify Marketplace v0.8.5
extension.js:1 Loaded Marketplace extension
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
adblock.js?time=1684285953449:49 Ads delayed: Adblock.js
gew1-spclient.spotify.com/remote-config-resolver/v3/configuration:1     Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:29 provider:transport resolve error T Object
m @ vendor~xpui.js:29
index.html:1 Uncaught (in promise) T
theme.js?time=1684285953646:1 Uncaught SyntaxError: Identifier 'DribbblishShared' has already been declared (at theme.js?time=1684285953646:1:1)
adblock.js?time=1684285953449:61 Disabled Esperanto ads Object
 The following functions are deprecated: googletag.pubads().setTagForChildDirectedTreatment(), googletag.pubads().clearTagForChildDirectedTreatment(), googletag.pubads().setRequestNonPersonalizedAds(), and googletag.pubads().setTagForUnderAgeOfConsent(). Please use googletag.pubads().setPrivacySettings() instead.
kx @ securepubads.g.doubl…1/pubads_impl.js:10
raw.githubusercontent.com/spicetify/spicetify-marketplace/main/manifest.json:1     Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:1969579)
    at onSuccess (xpui.js:1:1969393)
onError @ vendor~xpui.js:29
raw.githubusercontent.com/3raxton/spicetify-custom-apps-and-extensions/main/manifest.json:1     Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/TheRandomLabs/Scoop-Spotify/master/manifest.json:1     Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-hpto.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/8677.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/9801.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/3935.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-v2.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/5710.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
extension.js:1     GET https://raw.githubusercontent.com/itsmeow/Spicetify-Canvas/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
adblock.js?time=1684285953449:61 Disabled Esperanto ads {catalogue: 'free', app-developer: '0', type: 'free', ads: '1'}
xpui.js:1 Uncaught (in promise) NotFoundError: GET request to sp://ads/v1/settings/leaderboard failed with status code 404
    at l.onSuccess (xpui.js:1:1969579)
    at onSuccess (xpui.js:1:1969393)
onSuccess @ xpui.js:1
onSuccess @ xpui.js:1
extension.js:1     GET https://raw.githubusercontent.com/catppuccin/spicetify/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/getomni/spicetify/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/schnensch0/ziro/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Darkempire78/Fast-BlockTheSpot-And-Spicetify-Update/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/axieum/jasmine-spicetify-theme/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/yougotwill/Koushi/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Darkempire78/Dracula-Spicetify/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/okarin001/Onepunch/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/canbeardig/Spicetify-Orchis-Colours-v2/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Dueel/dotfiles/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/aiden04/spicetify-gui/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Vicente015/spicetify-config/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
```

**Specifics (please complete the following information):**
 - OS: Windows 10 x64
 - Spotify version 1.2.11.916.geb595a67
 - Spicetify version 2.18.1
 - Theme - Dribblish

**Comment by heshz** [comment]
Same thing+ colors are completely messed up✋😩

![image](https://github.com/spicetify/spicetify-themes/assets/133832839/25e36373-8e8e-43ee-bddd-538b17a97214)

**Comment by k1gen** [comment]
same: 
![image](https://github.com/spicetify/spicetify-themes/assets/62500387/17dec0de-06ea-448d-8cee-60beed2c6580)

**Comment by harbassan** [comment]
This is due to a new spotify update which changed around a bit of the layout, i'll get to it in a bit.
