### ISSUE TITLE
[Galaxy] 

### ISSUE THREAD

**Issue by Nikaito-m** [spicetify/spicetify-themes#938]
I'm using windows desktop version.  After updating the Spicetify version and refreshing the program, I saw that the theme was gone. I installed the galaxy theme using the marketplace and I tried to delete it and put it in again, didn't work. 
The Galaxy theme is not working as usual after the latest update from Spicetify.

**To Reproduce**
You just gotta try to use the theme and you will be able to see the problem.

**Expected behavior**
The Galaxy theme is expected to be as cool as always.

**Logs**

```console
extension.js:1 Initializing Spicetify Marketplace v0.8.5
extension.js:1 Loaded Marketplace extension
adblock.js?time=1685465061005:49 Ads delayed: Adblock.js
adblock.js?time=1685465061005:61 Disabled Esperanto ads Object
guc3-spclient.spotify.com/remote-config-resolver/v3/configuration:1     Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/spicetify/spicetify-marketplace/main/manifest.json:1     Failed to load resource: the server responded with a status of 404 ()
cdn.jsdelivr.net/gh/harbassan/spicetify-galaxy@main/galaxy.js?time=1685465061131:1     Failed to load resource: the server responded with a status of 404 ()
index.html:1 Refused to execute script from 'https://cdn.jsdelivr.net/gh/harbassan/spicetify-galaxy@main/galaxy.js?time=1685465061131' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
vendor~xpui.js:29 provider:transport resolve error T Object
m @ vendor~xpui.js:29
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
index.html:1 Uncaught (in promise) T
group-session.js?time=1685465061006:690 Found local device id (d469f59df83140d2680d8210c3fe19ead704d979)
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-hpto.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/5964.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/2774.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-v2.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/9801.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/5710.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
pubads_impl.js?cb=31074978:10 The following functions are deprecated: googletag.pubads().setTagForChildDirectedTreatment(), googletag.pubads().clearTagForChildDirectedTreatment(), googletag.pubads().setRequestNonPersonalizedAds(), and googletag.pubads().setTagForUnderAgeOfConsent(). Please use googletag.pubads().setPrivacySettings() instead.
hx @ pubads_impl.js?cb=31074978:10
(anonymous) @ pubads_impl.js?cb=31074978:10
(anonymous) @ pubads_impl.js?cb=31074978:10
(anonymous) @ pubads_impl.js?cb=31074978:10
(anonymous) @ pubads_impl.js?cb=31074978:10
(anonymous) @ pubads_impl.js?cb=31074978:10
(anonymous) @ about:srcdoc:242
29:46     GET https://s3.amazonaws.com/cream.public/js/ads-iframe-internal-click-tracking.js net::ERR_ABORTED 403 (Forbidden)
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:1778973)
    at onSuccess (xpui.js:1:1778787)
onError @ vendor~xpui.js:29
h @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
c @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.then (async)
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
c @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
extension.js:1     GET https://raw.githubusercontent.com/3raxton/spicetify-custom-apps-and-extensions/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/TheRandomLabs/Scoop-Spotify/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/itsmeow/Spicetify-Canvas/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
adblock.js?time=1685465061005:61 Disabled Esperanto ads {app-developer: '0'}
extension.js:1     GET https://raw.githubusercontent.com/getomni/spicetify/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/schnensch0/ziro/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Darkempire78/Fast-BlockTheSpot-And-Spicetify-Update/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/axieum/jasmine-spicetify-theme/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/yougotwill/Koushi/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Darkempire78/Dracula-Spicetify/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/okarin001/Onepunch/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/canbeardig/Spicetify-Orchis-Colours-v2/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Dueel/dotfiles/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Vicente015/spicetify-config/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/aiden04/spicetify-gui/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/th3an7/SpicetifyThings/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/spotify-util/ViewPlaylistsWithSong/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/amanharwara/spicetify-autoVolume/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/3raxton/NoSleep/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/yutakobayashidev/spotify-redesign/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/nm-nvan/spicetify-twitter/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Aluulu/spicetify-install-script/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/aetriusgx/spicetify-dark-mint/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/canbeardig/Spicetify-Orchis-Colours/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/shvedes/Gruvboxy/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/hrvstr/spicetify-macos-theme/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/AndrisRio/MoereauLibX/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/ethnzhng/Termify/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Daksh777/SpicetifyTheme/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Lylythii/SpicetifyAddons/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/zurrty/spicetify-night/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/misspent/Spicetify-Darkened/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/einzigartigerName/spicetify-history/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/elizabeth-c-chen/retreon-ziro/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/Coordinate-Cat/personal-spicetify/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/aaronbeckmann/spicetify-dribbblish-RGB/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/cyacedev/spicetify-FullBlack/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/h1toru/SPT/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/brickfrog/Xresources-spicetify/master/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/FlafyDev/spotify-listen-together-server/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/nmattis/spicetify-extensions/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/cj123/Sensibletify/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/spotify-util/BetterLeftSidebar/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/abh80/Spicetify-Fullscreen-Canvas/main/manifest.json 404
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
```

**Specifics:**
 - OS: [Windows]
 - Spotify version [1.2.12.902.g1924b088]
 - Spicetify version [v2.19.0.]
 - Theme Name [Galaxy]

Hope you can fix it,

**Comment by TwinTusks** [comment]
The latest update from Spotify broke a lot of themes. Please patiently wait for a fix update.

**Comment by kaiyin2** [comment]
> In the meantime, you can downgrade to Spotify version 1.2.10.760 here: https://spotify.en.uptodown.com/windows/download/101586881
> 
> Everything should work for the time being until the pull request by **sothatsbrendan** is reviewed and merged and the problem is fixed.
> 
> Make sure that after you install the previous version of Spotify you run:
> 
> ```
> spicetify backup
> spicetify apply
> ```
> 
> ### Important
> If you would like to **avoid future bugs like this**, you can choose to prevent Spotify from updating by following the instructions listed here: https://community.spotify.com/t5/Desktop-Windows/Stopping-Auto-update/td-p/4785101

**Comment by harbassan** [comment]
issue should be fixed now, let me know if it isnt.

**Comment by Nikaito-m** [comment]
It's working, thank u!
