### ISSUE TITLE
Matte, Dribbblish

### ISSUE THREAD

**Issue by birdlinux** [spicetify/spicetify-themes#958]
**Describe the bug**
Broken UI after applied themes, spotify having the "Something went wrong" error.

**To Reproduce**
1. Apply any theme and restart spotify

**Expected behavior**
I expect it to support the new UI which some themes already do. And to run properly

**Screenshots**
![image](https://github.com/spicetify/spicetify-themes/assets/123122904/dc0f7291-0d1f-491b-8c24-1526718b18b5)
![image](https://github.com/spicetify/spicetify-themes/assets/123122904/144866c7-3641-4cb2-9510-8d375ea4c42f)

**Logs**

```console
to load resource: net::ERR_NAME_NOT_RESOLVED
2vendor~xpui.js:1 ChunkLoadError: Loading chunk 9694 failed.
(missing: https://xpui.app.spotify.com/home-hpto.js)
    at o.f.j (xpui.js:1:2169554)
    at xpui.js:1:2164161
    at Array.reduce (<anonymous>)
    at o.e (xpui.js:1:2164139)
    at xpui.js:1:1405634
    at L (vendor~xpui.js:1:4845538)
    at Js (vendor~xpui.js:1:4660612)
    at Oc (vendor~xpui.js:1:4647313)
    at Tc (vendor~xpui.js:1:4647241)
    at Ac (vendor~xpui.js:1:4647104)
    at mc (vendor~xpui.js:1:4644091)
    at uc (vendor~xpui.js:1:4641447)
    at qc (vendor~xpui.js:1:4657362)
    at vendor~xpui.js:1:4658748
    at vc (vendor~xpui.js:1:4644469)
    at tl (vendor~xpui.js:1:4658733)
    at t.render (vendor~xpui.js:1:4666348)
    at xpui.js:1:1505367
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at hotloadWebpackModules (spicetifyWrapper.js:278:28)
    at o (vendor~xpui.js:1:146354)
2vendor~xpui.js:1 ChunkLoadError: Loading chunk 3635 failed.
(missing: https://xpui.app.spotify.com/3635.js)
    at o.f.j (xpui.js:1:2169554)
    at xpui.js:1:2164161
    at Array.reduce (<anonymous>)
    at o.e (xpui.js:1:2164139)
    at xpui.js:1:213838
    at L (vendor~xpui.js:1:4845538)
    at Js (vendor~xpui.js:1:4660612)
    at Oc (vendor~xpui.js:1:4647313)
    at Tc (vendor~xpui.js:1:4647241)
    at Ac (vendor~xpui.js:1:4647104)
    at mc (vendor~xpui.js:1:4644091)
    at vendor~xpui.js:1:4593829
    at t.unstable_runWithPriority (vendor~xpui.js:1:4865786)
    at ji (vendor~xpui.js:1:4593606)
    at Ki (vendor~xpui.js:1:4593774)
    at Ji (vendor~xpui.js:1:4593709)
    at De (vendor~xpui.js:1:4664792)
    at vendor~xpui.js:1:4585248
    at No (vendor~xpui.js:1:4585278)
    at Zt (vendor~xpui.js:1:4573356)
    at Xt (vendor~xpui.js:1:4572582)
    at t.unstable_runWithPriority (vendor~xpui.js:1:4865786)
    at qt (vendor~xpui.js:1:4572432)
    at HTMLDivElement.o (vendor~xpui.js:1:146354)
(anonymous) @ vendor~xpui.js:1
gew4-spclient.spotify.com/remote-config-resolver/v3/configuration:1     Failed to load resource: the server responded with a status of 404 ()
index.html:1 Uncaught (in promise) T
vendor~xpui.js:1 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:1970425)
    at onSuccess (xpui.js:1:1970239)
(anonymous) @ vendor~xpui.js:1
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-hpto.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/9331.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/3635.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-v2.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/1006.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Specifics (please complete the following information):**
 - OS: Pop OS 22.04
 - Spotify version [ 1.2.11.916.geb595a67]
 - Spicetify version [2.20.1]
 - Matte, Driblish

**Comment by harbassan** [comment]
This is not an issue related to the themes, you should probably just try reapplying spicetify.

**Comment by birdlinux** [comment]
i tried reapplying 50 times all give me the same result dude

**Comment by harbassan** [comment]
well it's definitely not because of the themes, especially matte considering it has no js. Probably just a wierd spicetify related bug. Maybe try reinstalling, or could ask somewhere else.
